import "@/styles/globals.css";
import ValueProvider from "@/components/values/valuesContext";
import Loading from "@/components/loading/loading";
import Terminal from "@/components/terminalComp";
import Navbar from "@/components/navbar/navbar";
import Head from "next/head";

export default function App({ Component, pageProps }) {
  return (
    <ValueProvider>
      <Head>
        <title>Ragib Ajmal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        ></link>
      </Head>
      <Loading></Loading>
      <Navbar />
      <Component {...pageProps} />
    </ValueProvider>
  );
}
